spring.application.name=APPbility

spring.jpa.hibernate.ddl-auto=create-drop

# Perfiles de trabajo.
spring.profiles.active=dev, pgsql

# Docker compose.
spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose.yml

# JWT.
jwt.secret=APPbilityLaMejorAPP
jwt.duration=1
jwt.refresh.duration=2

# Duracion en minutos.
activation.duration=5

# Sendgrid.
sendgrid.api.key=${SENDGRID_API_KEY}

# Resend.
#resend.api.key=${RESEND_API_KEY}


#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
