spring.application.name=APPbility

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# PERFILES DE TRABAJO ----------------------------------------------------------------------------


#(Descomentar para la ENTREGA FINAL).
#spring.profiles.active=dev, pgsql

#(Comentar para la ENTREGA FINAL).
spring.profiles.active=h2


# DOCKER COMPOSE --------------------------------------------------------------------------------


#(Comentar para la ENTREGA FINAL).
spring.docker.compose.enabled=false

#(Descomentar para la ENTREGA FINAL).
#spring.docker.compose.file=docker-compose.yml


# JWT -------------------------------------------------------------------------------------------


jwt.secret=APPbilityLaMejorAPPfgbdrgbdthdfbhryjnfdyherdthut6yfur6yfu6du

# El token tiene una vida util de 2 minutos.
jwt.duration=2

# El token de refresco tiene una vida util de 14 dias (20160 minutos).
jwt.refresh.duration=20160


# RELACIONADO A SEGURIDAD ----------------------------------------------------------------------


# Duracion en minutos.
activation.duration=5

# Sendgrid.
sendgrid.api.key=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


# SUBIDA DE ARCHIVOS ---------------------------------------------------------------------------


storage.location=./uploads

# Max attachment size
spring.servlet.multipart.max-file-size=5MB
# Max request size
spring.servlet.multipart.max-request-size=10MB

imgur.clientid=${IMGUR_CLIENTID:123456}

#logging.level.org.springframework.web=TRACE