spring.application.name=APPbility

spring.jpa.hibernate.ddl-auto=create-drop

# Perfiles de trabajo -----------------------------------------------------------------------------------------

spring.profiles.active=dev, pgsql

# Docker compose -----------------------------------------------------------------------------------------

spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose.yml

# JWT -----------------------------------------------------------------------------------------

jwt.secret=APPbilityLaMejorAPPfgbdrgbdthdfbhryjnfdyherdthut6yfur6yfu6du
jwt.duration=1
jwt.refresh.duration=2

# RELACIONADO A SEGURIDAD -----------------------------------------------------------------------------------------

# Duracion en minutos.
activation.duration=5

# Sendgrid.
sendgrid.api.key=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

# Resend.
#resend.api.key=${RESEND_API_KEY}

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SUBIDA DE ARCHIVOS -----------------------------------------------------------------------------------------

storage.location=./uploads

# Max attachment size
spring.servlet.multipart.max-file-size=5MB
# Max request size
spring.servlet.multipart.max-request-size=10MB

imgur.clientid=${IMGUR_CLIENTID:123456}
